"""Univers d'actions pour le Top/Flop — S&P 500 + grandes valeurs internationales.
TOUS cotés en USD (ADR US pour les étrangères) -> une seule devise, même séance.
Généré depuis la liste S&P 500 (datasets/s-and-p-500-companies) + ADR liquides.
"""

# {symbole_yahoo: nom_affiché}
UNIVERSE = {
    'A': 'Agilent Technologies',
    'AAPL': 'Apple',
    'ABBV': 'AbbVie',
    'ABNB': 'Airbnb',
    'ABT': 'Abbott Laboratories',
    'ACGL': 'Arch Capital',
    'ACN': 'Accenture',
    'ADBE': 'Adobe',
    'ADI': 'Analog Devices',
    'ADM': 'Archer Daniels Midla',
    'ADP': 'Automatic Data Proce',
    'ADSK': 'Autodesk',
    'AEE': 'Ameren',
    'AEP': 'American Electric Po',
    'AES': 'AES',
    'AFL': 'Aflac',
    'AIG': 'American Internation',
    'AIZ': 'Assurant',
    'AJG': 'Arthur J. Gallagher',
    'AKAM': 'Akamai Technologies',
    'ALB': 'Albemarle',
    'ALGN': 'Align Technology',
    'ALL': 'Allstate',
    'ALLE': 'Allegion',
    'AMAT': 'Applied Materials',
    'AMCR': 'Amcor',
    'AMD': 'Advanced Micro Devic',
    'AME': 'Ametek',
    'AMGN': 'Amgen',
    'AMP': 'Ameriprise Financial',
    'AMT': 'American Tower',
    'AMZN': 'Amazon',
    'ANET': 'Arista Networks',
    'AON': 'Aon',
    'AOS': 'A. O. Smith',
    'APA': 'APA',
    'APD': 'Air Products',
    'APH': 'Amphenol',
    'APO': 'Apollo Global Manage',
    'APP': 'AppLovin',
    'APTV': 'Aptiv',
    'ARE': 'Alexandria Real Esta',
    'ARES': 'Ares Management',
    'ASML': 'ASML',
    'ATO': 'Atmos Energy',
    'AVB': 'AvalonBay Communitie',
    'AVGO': 'Broadcom',
    'AVY': 'Avery Dennison',
    'AWK': 'American Water Works',
    'AXON': 'Axon Enterprise',
    'AXP': 'American Express',
    'AZN': 'AstraZeneca',
    'AZO': 'AutoZone',
    'BA': 'Boeing',
    'BAC': 'Bank of America',
    'BALL': 'Ball',
    'BAX': 'Baxter International',
    'BBVA': 'BBVA',
    'BBY': 'Best Buy',
    'BCS': 'Barclays',
    'BDX': 'Becton Dickinson',
    'BEN': 'Franklin Resources',
    'BF-B': 'Brown–Forman',
    'BG': 'Bunge Global',
    'BHP': 'BHP',
    'BIIB': 'Biogen',
    'BKNG': 'Booking',
    'BKR': 'Baker Hughes',
    'BLDR': 'Builders FirstSource',
    'BLK': 'BlackRock',
    'BMY': 'Bristol Myers Squibb',
    'BNY': 'BNY Mellon',
    'BP': 'BP',
    'BR': 'Broadridge Financial',
    'BRK-B': 'Berkshire Hathaway',
    'BRO': 'Brown & Brown',
    'BSX': 'Boston Scientific',
    'BTI': 'BAT',
    'BX': 'Blackstone',
    'BXP': 'BXP',
    'C': 'Citigroup',
    'CAG': 'Conagra Brands',
    'CAH': 'Cardinal Health',
    'CARR': 'Carrier Global',
    'CASY': "Casey's",
    'CAT': 'Caterpillar',
    'CB': 'Chubb Limited',
    'CBOE': 'Cboe Global Markets',
    'CBRE': 'CBRE',
    'CCI': 'Crown Castle',
    'CCL': 'Carnival',
    'CDNS': 'Cadence Design Syste',
    'CDW': 'CDW',
    'CEG': 'Constellation Energy',
    'CF': 'CF Industries',
    'CFG': 'Citizens Financial',
    'CHD': 'Church & Dwight',
    'CHRW': 'C.H. Robinson',
    'CHTR': 'Charter Communicatio',
    'CI': 'Cigna',
    'CIEN': 'Ciena',
    'CINF': 'Cincinnati Financial',
    'CL': 'Colgate-Palmolive',
    'CLX': 'Clorox',
    'CMCSA': 'Comcast',
    'CME': 'CME',
    'CMG': 'Chipotle Mexican Gri',
    'CMI': 'Cummins',
    'CMS': 'CMS Energy',
    'CNC': 'Centene',
    'CNI': 'Canadian National',
    'CNP': 'CenterPoint Energy',
    'COF': 'Capital One',
    'COHR': 'Coherent',
    'COIN': 'Coinbase',
    'COO': 'Cooper',
    'COP': 'ConocoPhillips',
    'COR': 'Cencora',
    'COST': 'Costco',
    'CP': 'Canadian Pacific',
    'CPAY': 'Corpay',
    'CPB': "Campbell's",
    'CPRT': 'Copart',
    'CPT': 'Camden Property Trus',
    'CRH': 'CRH',
    'CRL': 'Charles River Labora',
    'CRM': 'Salesforce',
    'CRWD': 'CrowdStrike',
    'CSCO': 'Cisco',
    'CSGP': 'CoStar',
    'CSX': 'CSX',
    'CTAS': 'Cintas',
    'CTSH': 'Cognizant',
    'CTVA': 'Corteva',
    'CVNA': 'Carvana',
    'CVS': 'CVS Health',
    'CVX': 'Chevron',
    'D': 'Dominion Energy',
    'DAL': 'Delta Air Lines',
    'DASH': 'DoorDash',
    'DB': 'Deutsche Bank',
    'DD': 'DuPont',
    'DDOG': 'Datadog',
    'DE': 'Deere',
    'DECK': 'Deckers Brands',
    'DELL': 'Dell Technologies',
    'DEO': 'Diageo',
    'DG': 'Dollar General',
    'DGX': 'Quest Diagnostics',
    'DHI': 'D. R. Horton',
    'DHR': 'Danaher',
    'DIS': 'Walt Disney',
    'DLR': 'Digital Realty',
    'DLTR': 'Dollar Tree',
    'DOC': 'Healthpeak Propertie',
    'DOV': 'Dover',
    'DOW': 'Dow',
    'DPZ': "Domino's",
    'DRI': 'Darden Restaurants',
    'DTE': 'DTE Energy',
    'DUK': 'Duke Energy',
    'DVA': 'DaVita',
    'DVN': 'Devon Energy',
    'DXCM': 'Dexcom',
    'E': 'Eni',
    'EA': 'Electronic Arts',
    'EBAY': 'eBay',
    'ECL': 'Ecolab',
    'ED': 'Consolidated Edison',
    'EFX': 'Equifax',
    'EG': 'Everest',
    'EIX': 'Edison International',
    'EL': 'Estée Lauder',
    'ELV': 'Elevance Health',
    'EME': 'Emcor',
    'EMR': 'Emerson Electric',
    'ENB': 'Enbridge',
    'EOG': 'EOG Resources',
    'EQIX': 'Equinix',
    'EQR': 'Equity Residential',
    'EQT': 'EQT',
    'ERIC': 'Ericsson',
    'ERIE': 'Erie Indemnity',
    'ES': 'Eversource Energy',
    'ESS': 'Essex Property Trust',
    'ETN': 'Eaton',
    'ETR': 'Entergy',
    'EVRG': 'Evergy',
    'EW': 'Edwards Lifesciences',
    'EXC': 'Exelon',
    'EXE': 'Expand Energy',
    'EXPD': 'Expeditors Internati',
    'EXPE': 'Expedia',
    'EXR': 'Extra Space Storage',
    'F': 'Ford Motor',
    'FANG': 'Diamondback Energy',
    'FAST': 'Fastenal',
    'FCX': 'Freeport-McMoRan',
    'FDS': 'FactSet',
    'FDX': 'FedEx',
    'FDXF': 'FedEx Freight',
    'FE': 'FirstEnergy',
    'FFIV': 'F5',
    'FICO': 'Fair Isaac',
    'FIS': 'Fidelity National In',
    'FISV': 'Fiserv',
    'FITB': 'Fifth Third Bancorp',
    'FIX': 'Comfort Systems USA',
    'FOX': 'Fox',
    'FOXA': 'Fox',
    'FRT': 'Federal Realty Inves',
    'FSLR': 'First Solar',
    'FTNT': 'Fortinet',
    'FTV': 'Fortive',
    'GD': 'General Dynamics',
    'GDDY': 'GoDaddy',
    'GE': 'GE Aerospace',
    'GEHC': 'GE HealthCare',
    'GEN': 'Gen Digital',
    'GEV': 'GE Vernova',
    'GILD': 'Gilead Sciences',
    'GIS': 'General Mills',
    'GL': 'Globe Life',
    'GLW': 'Corning',
    'GM': 'General Motors',
    'GNRC': 'Generac',
    'GOOG': 'Alphabet',
    'GOOGL': 'Alphabet',
    'GPC': 'Genuine Parts',
    'GPN': 'Global Payments',
    'GRMN': 'Garmin',
    'GS': 'Goldman Sachs',
    'GSK': 'GSK',
    'GWW': 'W. W. Grainger',
    'HAL': 'Halliburton',
    'HAS': 'Hasbro',
    'HBAN': 'Huntington Bancshare',
    'HCA': 'HCA Healthcare',
    'HD': 'Home Depot',
    'HIG': 'Hartford',
    'HII': 'Huntington Ingalls I',
    'HLT': 'Hilton Worldwide',
    'HMC': 'Honda',
    'HON': 'Honeywell',
    'HOOD': 'Robinhood Markets',
    'HPE': 'Hewlett Packard Ente',
    'HPQ': 'HP',
    'HRL': 'Hormel Foods',
    'HSBC': 'HSBC',
    'HSIC': 'Henry Schein',
    'HST': 'Host Hotels & Resort',
    'HSY': 'Hershey',
    'HUBB': 'Hubbell Incorporated',
    'HUM': 'Humana',
    'HWM': 'Howmet Aerospace',
    'IBKR': 'Interactive Brokers',
    'IBM': 'IBM',
    'ICE': 'Intercontinental Exc',
    'IDXX': 'Idexx Laboratories',
    'IEX': 'IDEX',
    'IFF': 'International Flavor',
    'INCY': 'Incyte',
    'ING': 'ING',
    'INTC': 'Intel',
    'INTU': 'Intuit',
    'INVH': 'Invitation Homes',
    'IP': 'International Paper',
    'IQV': 'IQVIA',
    'IR': 'Ingersoll Rand',
    'IRM': 'Iron Mountain',
    'ISRG': 'Intuitive Surgical',
    'IT': 'Gartner',
    'ITW': 'Illinois Tool Works',
    'IVZ': 'Invesco',
    'J': 'Jacobs Solutions',
    'JBHT': 'J.B. Hunt',
    'JBL': 'Jabil',
    'JCI': 'Johnson Controls',
    'JKHY': 'Jack Henry & Associa',
    'JNJ': 'Johnson & Johnson',
    'JPM': 'JPMorgan Chase',
    'KDP': 'Keurig Dr Pepper',
    'KEY': 'KeyCorp',
    'KEYS': 'Keysight Technologie',
    'KHC': 'Kraft Heinz',
    'KIM': 'Kimco Realty',
    'KKR': 'KKR',
    'KLAC': 'KLA',
    'KMB': 'Kimberly-Clark',
    'KMI': 'Kinder Morgan',
    'KO': 'Coca-Cola',
    'KR': 'Kroger',
    'KVUE': 'Kenvue',
    'L': 'Loews',
    'LDOS': 'Leidos',
    'LEN': 'Lennar',
    'LH': 'Labcorp',
    'LHX': 'L3Harris',
    'LII': 'Lennox International',
    'LIN': 'Linde',
    'LITE': 'Lumentum',
    'LLY': 'Lilly (Eli)',
    'LMT': 'Lockheed Martin',
    'LNT': 'Alliant Energy',
    'LOW': "Lowe's",
    'LRCX': 'Lam Research',
    'LULU': 'Lululemon Athletica',
    'LUV': 'Southwest Airlines',
    'LVMUY': 'LVMH',
    'LVS': 'Las Vegas Sands',
    'LYB': 'LyondellBasell',
    'LYV': 'Live Nation Entertai',
    'MA': 'Mastercard',
    'MAA': 'Mid-America Apartmen',
    'MAR': 'Marriott Internation',
    'MAS': 'Masco',
    'MCD': "McDonald's",
    'MCHP': 'Microchip Technology',
    'MCK': 'McKesson',
    'MCO': "Moody's",
    'MDLZ': 'Mondelez Internation',
    'MDT': 'Medtronic',
    'MET': 'MetLife',
    'META': 'Meta Platforms',
    'MGM': 'MGM Resorts',
    'MKC': 'McCormick',
    'MLM': 'Martin Marietta Mate',
    'MMM': '3M',
    'MNST': 'Monster Beverage',
    'MO': 'Altria',
    'MOS': 'Mosaic',
    'MPC': 'Marathon Petroleum',
    'MPWR': 'Monolithic Power Sys',
    'MRK': 'Merck',
    'MRNA': 'Moderna',
    'MRSH': 'Marsh McLennan',
    'MS': 'Morgan Stanley',
    'MSCI': 'MSCI',
    'MSFT': 'Microsoft',
    'MSI': 'Motorola Solutions',
    'MTB': 'M&T Bank',
    'MTD': 'Mettler Toledo',
    'MU': 'Micron Technology',
    'MUFG': 'Mitsubishi UFJ',
    'NCLH': 'Norwegian Cruise Lin',
    'NDAQ': 'Nasdaq',
    'NDSN': 'Nordson',
    'NEE': 'NextEra Energy',
    'NEM': 'Newmont',
    'NFLX': 'Netflix',
    'NI': 'NiSource',
    'NKE': 'Nike',
    'NMR': 'Nomura',
    'NOC': 'Northrop Grumman',
    'NOW': 'ServiceNow',
    'NRG': 'NRG Energy',
    'NSC': 'Norfolk Southern',
    'NSRGY': 'Nestlé',
    'NTAP': 'NetApp',
    'NTRS': 'Northern Trust',
    'NUE': 'Nucor',
    'NVDA': 'Nvidia',
    'NVO': 'Novo Nordisk',
    'NVR': 'NVR',
    'NVS': 'Novartis',
    'NWS': 'News',
    'NWSA': 'News',
    'NXPI': 'NXP Semiconductors',
    'O': 'Realty Income',
    'ODFL': 'Old Dominion',
    'OKE': 'Oneok',
    'OMC': 'Omnicom',
    'ON': 'ON Semiconductor',
    'ORCL': 'Oracle',
    'ORLY': 'O’Reilly Automotive',
    'OTIS': 'Otis Worldwide',
    'OXY': 'Occidental Petroleum',
    'PANW': 'Palo Alto Networks',
    'PAYX': 'Paychex',
    'PCAR': 'Paccar',
    'PCG': 'PG&E',
    'PEG': 'Public Service Enter',
    'PEP': 'PepsiCo',
    'PFE': 'Pfizer',
    'PFG': 'Principal Financial',
    'PG': 'Procter & Gamble',
    'PGR': 'Progressive',
    'PH': 'Parker Hannifin',
    'PHG': 'Philips',
    'PHM': 'PulteGroup',
    'PKG': 'Packaging Corporatio',
    'PLD': 'Prologis',
    'PLTR': 'Palantir Technologie',
    'PM': 'Philip Morris Intern',
    'PNC': 'PNC Financial Servic',
    'PNR': 'Pentair',
    'PNW': 'Pinnacle West Capita',
    'PODD': 'Insulet',
    'POOL': 'Pool',
    'PPG': 'PPG Industries',
    'PPL': 'PPL',
    'PRU': 'Prudential Financial',
    'PSA': 'Public Storage',
    'PSKY': 'Paramount Skydance',
    'PSX': 'Phillips 66',
    'PTC': 'PTC',
    'PWR': 'Quanta Services',
    'PYPL': 'PayPal',
    'Q': 'Qnity Electronics',
    'QCOM': 'Qualcomm',
    'RCL': 'Royal Caribbean',
    'REG': 'Regency Centers',
    'REGN': 'Regeneron Pharmaceut',
    'RF': 'Regions Financial',
    'RHHBY': 'Roche',
    'RIO': 'Rio Tinto',
    'RJF': 'Raymond James Financ',
    'RL': 'Ralph Lauren',
    'RMD': 'ResMed',
    'ROK': 'Rockwell Automation',
    'ROL': 'Rollins',
    'ROP': 'Roper Technologies',
    'ROST': 'Ross Stores',
    'RSG': 'Republic Services',
    'RTX': 'RTX',
    'RVTY': 'Revvity',
    'RY': 'Royal Bank Canada',
    'SAN': 'Santander',
    'SAP': 'SAP',
    'SATS': 'EchoStar',
    'SBAC': 'SBA Communications',
    'SBUX': 'Starbucks',
    'SCHW': 'Charles Schwab',
    'SHEL': 'Shell',
    'SHOP': 'Shopify',
    'SHW': 'Sherwin-Williams',
    'SIEGY': 'Siemens',
    'SJM': 'J.M. Smucker',
    'SLB': 'Schlumberger',
    'SMCI': 'Supermicro',
    'SMFG': 'Sumitomo Mitsui',
    'SNA': 'Snap-on',
    'SNDK': 'Sandisk',
    'SNPS': 'Synopsys',
    'SNY': 'Sanofi',
    'SO': 'Southern',
    'SOLV': 'Solventum',
    'SONY': 'Sony',
    'SPG': 'Simon Property',
    'SPGI': 'S&P Global',
    'SPOT': 'Spotify',
    'SRE': 'Sempra',
    'STE': 'Steris',
    'STLA': 'Stellantis',
    'STLD': 'Steel Dynamics',
    'STT': 'State Street',
    'STX': 'Seagate Technology',
    'STZ': 'Constellation Brands',
    'SU': 'Suncor',
    'SW': 'Smurfit Westrock',
    'SWK': 'Stanley Black & Deck',
    'SWKS': 'Skyworks Solutions',
    'SYF': 'Synchrony Financial',
    'SYK': 'Stryker',
    'SYY': 'Sysco',
    'T': 'AT&T',
    'TAP': 'Molson Coors Beverag',
    'TD': 'TD Bank',
    'TDG': 'TransDigm',
    'TDY': 'Teledyne Technologie',
    'TECH': 'Bio-Techne',
    'TEL': 'TE Connectivity',
    'TER': 'Teradyne',
    'TFC': 'Truist Financial',
    'TGT': 'Target',
    'TJX': 'TJX',
    'TKO': 'TKO',
    'TM': 'Toyota',
    'TMO': 'Thermo Fisher Scient',
    'TMUS': 'T-Mobile US',
    'TPL': 'Texas Pacific Land',
    'TPR': 'Tapestry',
    'TRGP': 'Targa Resources',
    'TRMB': 'Trimble',
    'TROW': 'T. Rowe Price',
    'TRV': 'Travelers',
    'TSCO': 'Tractor Supply',
    'TSLA': 'Tesla',
    'TSN': 'Tyson Foods',
    'TT': 'Trane Technologies',
    'TTD': 'Trade Desk',
    'TTE': 'TotalEnergies',
    'TTWO': 'Take-Two Interactive',
    'TXN': 'Texas Instruments',
    'TXT': 'Textron',
    'TYL': 'Tyler Technologies',
    'UAL': 'United Airlines',
    'UBER': 'Uber',
    'UBS': 'UBS',
    'UDR': 'UDR',
    'UHS': 'Universal Health Ser',
    'UL': 'Unilever',
    'ULTA': 'Ulta Beauty',
    'UNH': 'UnitedHealth',
    'UNP': 'Union Pacific',
    'UPS': 'United Parcel Servic',
    'URI': 'United Rentals',
    'USB': 'U.S. Bancorp',
    'V': 'Visa',
    'VEEV': 'Veeva Systems',
    'VICI': 'Vici Properties',
    'VLO': 'Valero Energy',
    'VLTO': 'Veralto',
    'VMC': 'Vulcan Materials',
    'VRSK': 'Verisk Analytics',
    'VRSN': 'Verisign',
    'VRT': 'Vertiv',
    'VRTX': 'Vertex Pharmaceutica',
    'VST': 'Vistra',
    'VTR': 'Ventas',
    'VTRS': 'Viatris',
    'VZ': 'Verizon',
    'WAB': 'Wabtec',
    'WAT': 'Waters',
    'WBD': 'Warner Bros. Discove',
    'WDAY': 'Workday',
    'WDC': 'Western Digital',
    'WEC': 'WEC Energy',
    'WELL': 'Welltower',
    'WFC': 'Wells Fargo',
    'WM': 'Waste Management',
    'WMB': 'Williams',
    'WMT': 'Walmart',
    'WRB': 'W. R. Berkley',
    'WSM': 'Williams-Sonoma',
    'WST': 'West Pharmaceutical ',
    'WTW': 'Willis Towers Watson',
    'WY': 'Weyerhaeuser',
    'WYNN': 'Wynn Resorts',
    'XEL': 'Xcel Energy',
    'XOM': 'ExxonMobil',
    'XYL': 'Xylem',
    'XYZ': 'Block',
    'YUM': 'Yum! Brands',
    'ZBH': 'Zimmer Biomet',
    'ZBRA': 'Zebra Technologies',
    'ZTS': 'Zoetis',
}
